#!/usr/bin/env bash
#Install nginx web server on port 80.

sudo apt-get update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/server {/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;  }' /etc/nginx/sites-available/default
service nginx start
