#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Remove the default site configuration
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the available site configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service
service nginx restart
